{% set name = "influx-cli" %}
{% set version = "2.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/influxdata/influx-cli/archive/v{{ version }}.tar.gz
  sha256: 2741105c0fa7bf0f728643807aa21e9a8e356b17a681e92f06c4ff680e6944ac

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - influx-cli --help

about:
  home: https://github.com/influxdata/influx-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: CLI for managing resources in InfluxDB v2
  dev_url: https://github.com/influxdata/influx-cli

extra:
  recipe-maintainers:
    - danielnachun
